server:
  port: 8081

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.aula-spring #topic
      routing-key:
        producer: rk.producer.aula-spring #queue
      deadletter:
        producer: dl.producer.aula-spring #dlq

