server:
  port: 8081

spring:
  application:
    name: integrations-amqp
  datasource:
    url: jdbc:postgresql://localhost:5432/integrations_amqp
    password: postgres
    username: postgres
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.employee
      routing-key:
        producer: rk.producer.employee
      deadletter:
        producer: dl.producer.employee
  config:
    import: optional:configserver:htp://localhost:8081
